
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

public class BookBorrowGUI extends javax.swing.JPanel {

	private Member member;
	private Book book;

	public BookBorrowGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Accession Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("To Borrow a Book, Please Enter Requested Information Below:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel6)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(14, 14, 14))
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Membership ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 204, 153));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Borrow Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 153));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Back to Loans Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2)
                                .addComponent(jTextField1)))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

		EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("org.hibernate.als.jpa");
		EntityManager entityManager = entityManagerFactory.createEntityManager();

		Date currentDate = new java.util.Date();
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		Calendar cal = Calendar.getInstance();
		cal.setTime(currentDate);
		cal.add(Calendar.DAY_OF_MONTH, 14);
		Date dueDate = cal.getTime();

		entityManager.getTransaction().begin();
		Book bookToBorrow = entityManager.find(Book.class, jTextField1.getText());
		Member withdrawingMember = entityManager.find(Member.class, jTextField2.getText());

		if (bookToBorrow == null) {
			MainMenuGUI mainMenu = new MainMenuGUI();
			JOptionPane.showMessageDialog(mainMenu, "Invalid Book!");
		} else if (withdrawingMember == null) {
			MainMenuGUI mainMenu = new MainMenuGUI();
			JOptionPane.showMessageDialog(mainMenu, "Invalid Member!");
		} else {
			String message = "Confirm Loan Details to Be Correct \n";
			message += "Accession Number: " + bookToBorrow.getAccessionNumber() + "\n";
			message += "Book Title: " + bookToBorrow.getTitle() + "\n";
			message += "Borrow Date: " + sdf.format(currentDate) + "\n";
			message += "Membership ID: " + withdrawingMember.getId() + "\n";
			message += "Member Name: " + withdrawingMember.getName() + "\n";
			message += "Due Date: " + sdf.format(dueDate);

			int selected = JOptionPane.showConfirmDialog(null, message, "Confirmation", JOptionPane.YES_NO_OPTION);

			Query query1 = entityManager.createNativeQuery("SELECT * FROM Book WHERE memberId LIKE :id ", Book.class);
			query1.setParameter("id", "%" + withdrawingMember.getId() + "%");
			int numOfborrowedBooks = query1.getResultList().size();

			Query query2 = entityManager.createNativeQuery("SELECT * FROM Book WHERE memberReturnId LIKE :id ", Book.class);
			query2.setParameter("id", "%" + withdrawingMember.getId() + "%");
			int numOfReturnedBooks = query2.getResultList().size();

			int numOfFinalBorrowedBooks = numOfborrowedBooks - numOfReturnedBooks;

			Query query3 = entityManager.createNativeQuery("SELECT * FROM Fine WHERE memberId LIKE :id", Fine.class);
			query3.setParameter("id", "%" + withdrawingMember.getId() + "%");
			int numOfFines = query3.getResultList().size();

			if (selected == JOptionPane.YES_OPTION) {
				try {
					if (bookToBorrow.getBorrowDate() == null && numOfFinalBorrowedBooks < 2 && numOfFines == 0) {
						bookToBorrow.setMemberId(jTextField2.getText());
						bookToBorrow.setBorrowDate(currentDate);
						bookToBorrow.setDueDate(dueDate);
						bookToBorrow.setMemberRId(null);
						bookToBorrow.setReserveDate(null);
						bookToBorrow.setReturnDate(null);
						bookToBorrow.setMemberReturnId(null);

						entityManager.persist(bookToBorrow);
						entityManager.getTransaction().commit();

						MainMenuGUI mainMenu = new MainMenuGUI();
						JOptionPane.showMessageDialog(mainMenu, "Success! Book borrowed.");

					} else if (bookToBorrow.getReturnDate() == null) {
						MainMenuGUI mainMenu = new MainMenuGUI();
						JOptionPane.showMessageDialog(mainMenu, "Error! Book has not been returned yet");
					} else if (numOfFinalBorrowedBooks == 2) {
						MainMenuGUI mainMenu = new MainMenuGUI();
						JOptionPane.showMessageDialog(mainMenu, "Error! Member loan quota exceeded.");

					} else if (bookToBorrow.getBorrowDate() != null && bookToBorrow.getReturnDate() == null) {
						MainMenuGUI mainMenu = new MainMenuGUI();
						JOptionPane.showMessageDialog(mainMenu, "Error! Book currently on loan until: " + bookToBorrow.getDueDate());

					} else if (bookToBorrow.getBorrowDate() != null && bookToBorrow.getBorrowDate().compareTo(bookToBorrow.getReturnDate()) >= 0 && !bookToBorrow.getMemberId().equals(bookToBorrow.getMemberReturnId())) {
						MainMenuGUI mainMenu = new MainMenuGUI();
						JOptionPane.showMessageDialog(mainMenu, "Error! Book currently on loan until: " + bookToBorrow.getDueDate());

					} else if (currentDate.compareTo(bookToBorrow.getReturnDate()) < 0) {
						MainMenuGUI mainMenu = new MainMenuGUI();
						JOptionPane.showMessageDialog(mainMenu, "Error! Book has not been returned yet");

					} else if (bookToBorrow.getMemberRId() != null && !bookToBorrow.getMemberRId().equals(withdrawingMember.getId())) {
						MainMenuGUI mainMenu = new MainMenuGUI();
						JOptionPane.showMessageDialog(mainMenu, "Error! Another member has already reserved this book and it cannot be loaned");
					} else if (numOfFines > 0) {
						MainMenuGUI mainMenu = new MainMenuGUI();
						JOptionPane.showMessageDialog(mainMenu, "Member has outstanding fines.");
					} else {
						bookToBorrow.setMemberId(jTextField2.getText());
						bookToBorrow.setBorrowDate(currentDate);
						bookToBorrow.setDueDate(dueDate);
						bookToBorrow.setMemberRId(null);
						bookToBorrow.setReserveDate(null);
						bookToBorrow.setReturnDate(null);
						bookToBorrow.setMemberReturnId(null);

						entityManager.persist(bookToBorrow);
						entityManager.getTransaction().commit();

						MainMenuGUI mainMenu = new MainMenuGUI();
						JOptionPane.showMessageDialog(mainMenu, "Success! Book borrowed.");
					}
				} catch (NullPointerException ex) {
					System.out.print("NullPointerException Caught");

				}
			}
		}

		entityManagerFactory.close();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		LoanSelectGUI loanSelectPage = new LoanSelectGUI();

		removeAll();
		setLayout(new BorderLayout());
		add(loanSelectPage);
		validate();
		repaint();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
